"""
Evaluation metrics for LLMOps A/B testing.

Same metric logic as rag-evaluation-suite (Project 2) but standalone here —
no LangChain dependency required for the core metrics.

Metrics:
  - Context Precision: pure Python Jaccard similarity (no API cost)
  - Faithfulness: LLM judge via Groq (uses InferenceGateway)
  - Answer Relevancy: embedding cosine similarity (HuggingFace, local)
"""
import json
import re
import statistics
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

STOPWORDS = {
    "a", "an", "the", "is", "it", "in", "on", "at", "to", "for",
    "of", "and", "or", "but", "not", "with", "this", "that", "are",
    "was", "were", "be", "been", "have", "has", "had", "do", "does",
    "did", "will", "would", "could", "should", "may", "might", "can",
    "its", "from", "by", "as",
}


def _tokenize(text: str) -> set:
    tokens = re.findall(r"\b[a-z]{3,}\b", text.lower())
    return {t for t in tokens if t not in STOPWORDS}


def _jaccard(a: set, b: set) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def compute_context_precision(
    question: str, contexts: List[str], threshold: float = 0.05
) -> float:
    """
    Fraction of retrieved chunks that share vocabulary with the question.
    Pure Python, no API call needed.
    """
    if not contexts:
        return 0.0
    q_tokens = _tokenize(question)
    relevant = sum(
        1 for c in contexts if _jaccard(q_tokens, _tokenize(c)) >= threshold
    )
    return round(relevant / len(contexts), 4)


def compute_faithfulness(
    answer: str,
    context_texts: List[str],
    gateway,
    prompt_name: str = "faithfulness_judge",
) -> float:
    """
    LLM judge: what fraction of claims in the answer are supported by the context?
    Returns score in [0, 1]. 1.0 = fully faithful, 0.0 = entirely hallucinated.
    """
    context_block = "\n\n---\n\n".join(context_texts)
    judge_prompt = f"""You are a faithful answer evaluator.

Context provided to the LLM:
{context_block}

Answer generated by the LLM:
{answer}

Task: Identify all distinct factual claims in the answer. For each, determine if it is
directly supported by the context above (not by general knowledge).

Respond ONLY with valid JSON in this exact format:
{{
  "total_claims": <integer>,
  "unsupported_claims": [<string>, ...]
}}"""

    result = gateway.generate(
        prompt_name=prompt_name,
        rendered_prompt=judge_prompt,
        prompt_version="builtin",
    )

    if not result.success or not result.answer:
        return 0.5  # Neutral on error

    raw = result.answer.strip()
    # Strip markdown code fences
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        parsed = json.loads(raw)
        total = int(parsed.get("total_claims", 1))
        unsupported = len(parsed.get("unsupported_claims", []))
        if total <= 0:
            return 1.0
        return round(max(0.0, 1.0 - unsupported / total), 4)
    except (json.JSONDecodeError, KeyError, TypeError):
        return 0.5


def compute_answer_relevancy(
    question: str,
    answer: str,
    gateway,
    embeddings,
    prompt_name: str = "relevancy_judge",
    n_synthetic: int = 3,
) -> float:
    """
    Cosine similarity between question and synthetic questions generated from the answer.
    High score = answer addresses what was actually asked.
    """
    if not answer.strip():
        return 0.0

    synth_prompt = f"""Given the following answer, generate exactly {n_synthetic} diverse
questions that this answer could be responding to.
Return ONLY a JSON array of strings. No explanation.

Answer:
{answer}

Questions JSON array:"""

    result = gateway.generate(
        prompt_name=prompt_name,
        rendered_prompt=synth_prompt,
        prompt_version="builtin",
    )

    if not result.success or not result.answer:
        return 0.0

    raw = result.answer.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        synth_questions = json.loads(raw)
        if not isinstance(synth_questions, list) or not synth_questions:
            return 0.0
    except json.JSONDecodeError:
        return 0.0

    # Embed original question and synthetic questions
    try:
        q_embed = embeddings.embed_query(question)
        similarities = []
        for sq in synth_questions[:n_synthetic]:
            sq_embed = embeddings.embed_query(str(sq))
            # Cosine similarity (embeddings are normalized → dot product == cosine)
            dot = sum(a * b for a, b in zip(q_embed, sq_embed))
            similarities.append(max(0.0, dot))
        return round(statistics.mean(similarities), 4) if similarities else 0.0
    except Exception:
        return 0.0


@dataclass
class EvalResult:
    question: str
    answer: str
    context_precision: float
    faithfulness: float
    answer_relevancy: float
    latency_ms: int
    top_k: int

    def overall_score(self) -> float:
        return round(
            0.3 * self.context_precision
            + 0.4 * self.faithfulness
            + 0.3 * self.answer_relevancy,
            4,
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "question": self.question,
            "answer": self.answer,
            "context_precision": round(self.context_precision, 3),
            "faithfulness": round(self.faithfulness, 3),
            "answer_relevancy": round(self.answer_relevancy, 3),
            "overall_score": self.overall_score(),
            "latency_ms": self.latency_ms,
        }

    def as_metrics_dict(self) -> Dict[str, float]:
        return {
            "context_precision": self.context_precision,
            "faithfulness": self.faithfulness,
            "answer_relevancy": self.answer_relevancy,
            "overall_score": self.overall_score(),
            "latency_ms": float(self.latency_ms),
        }


def summarize_results(results: List[EvalResult]) -> Dict[str, Any]:
    if not results:
        return {}
    return {
        "mean_context_precision": round(statistics.mean(r.context_precision for r in results), 4),
        "mean_faithfulness": round(statistics.mean(r.faithfulness for r in results), 4),
        "mean_answer_relevancy": round(statistics.mean(r.answer_relevancy for r in results), 4),
        "mean_overall_score": round(statistics.mean(r.overall_score() for r in results), 4),
        "mean_latency_ms": round(statistics.mean(r.latency_ms for r in results)),
        "total_evaluated": len(results),
    }
